---
title: "transition_reveal"
author: "Robbie Bonelli"
date: "22/11/2018"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE,echo=F}
library(gganimate)
library(dplyr)
library(readxl)
knitr::opts_chunk$set(echo = TRUE,cache = T)

rm(list=ls())


dat <- read_excel("~/Desktop/workshops/rpdr_data.xlsx")
head(dat)
dat$Notes <- NULL
dat[is.na(dat)] <- 0
dat$time <- dat$Start

airquality <- airquality
```

# What does `transition_reveal()` do?

> transition_reveal() allows you to let data gradually appear, based on a given time dimension. 


The function needs two simple paramteres, **id** and **along**.

Look at this plot

```{r}
p <- ggplot(airquality, aes(Day, Temp, group = Month)) +
  geom_line()

p

```


We can try to track down each month's (**id**) temperature along the day (**along**)

```{r}
p <- ggplot(airquality, aes(Day, Temp, group = Month)) +
  geom_line()+
  transition_reveal(id=Month, along=Day)

animate(p,nframes = 50)
```


We can try to visualise how all months move by also tacking them down

```{r}
airquality$month_name <- rep(c("May","June","July","August","September"),c(31, 30, 31 ,31 ,30 ))


p <- ggplot(airquality, aes(Day, Temp, group = Month,color=month_name)) +
  geom_line()+
  geom_text(aes(label=month_name))+
  transition_reveal(id=Month, along=Day)

animate(p,nframes = 50)
```




















