---
title: "view_follow"
author: "Danielle Navarro"
date: "22/11/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gapminder)
library(gganimate)
```


## Creating the animation

Let's start with the `gapminder` animation from the gganimate github page:

```{r, initialanimation, cache=TRUE}
pic <- gapminder %>% filter(continent == "Africa") %>%
  ggplot(aes(
    x = log10(gdpPercap), y = lifeExp, 
    size = pop, colour = country
  )) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) 

anim <- pic + 
  labs(
    title = 'Year: {frame_time}', 
    x = 'GDP Per Capita (log10)', 
    y = 'Life Expectancy') +
  transition_time(year) +
  ease_aes('linear')

anim %>% animate(type = "cairo")
```


## Zooming in with view_follow

```{r, viewfollow1, cache = TRUE}
anim2 <- anim + view_follow()
anim2 %>% animate(type = "cairo")
```


## Interaction with shadow_wake

```{r, viewfollow2, cache = TRUE}
anim3 <- anim + view_follow() + shadow_wake(.1)
anim3 %>% animate(type = "cairo", detail= 5)
```

